### ISSUE TITLE
Allows to run the server with a custom port -- `wp serve -p`

### ISSUE THREAD

**Issue by kasunben** [kodeflex/wp-artisan#2]
```
wp serve
wp serve --port 8080
```

### Tasks
* [x] Update `promptSchema` for server configs:
```
  {
    type: 'input',
    name: 'serverHost',
    message: 'Enter the site url',
    default: 'localhost'
  },
  {
    type: 'input',
    name: 'serverPort',
    message: 'Enter the the port number',
    default: '8081'
  },
```
* [x] Change `templates/site.json.tpl`
```
{
  "siteName": "<%= siteName %>",
  ...
  "db": {
    ...
  },
  "server": {
      host: "<%= serverHost %>",
      port: "<%= serverPort %>"
  }
}
```
* [x] Save server configs. in `site.json`

On every time, user runs `wp serve` command;
- Fetch server settings from `site.json` and run the server according to that.

When user try to run the server with `wp serve -p 8080`;
- Fetch server settings from `site.json`
- If user provided port number and the one in `site.json` are not the same;
     - Update them in `site.json`, `wp-config.json` and the `database`
- Run the server

**Comment by kasunben** [comment]
Fix #4

**Comment by kasunben** [comment]
This issue was moved to 99xt/wp-artisan#4
